# Generated by Django 3.1.1 on 2020-10-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200923_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('permissions', models.ManyToManyField(blank=True, to='app.Company')),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='company_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
    ]
