branch-defaults:
  default:
    environment: TrckpckBackend-env
environment-defaults:
  TrckpckBackend-env:
    branch: null
    repository: null
global:
  application_name: trckpck_backend
  default_ec2_keyname: null
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
